### ISSUE TITLE
Set up CI/CD pipeline for automated testing and npm publishing

### ISSUE THREAD

**Issue by galligan** [maybe-good/prompts#5]
## Description
Configure GitHub Actions for continuous integration and automated npm publishing.

### CI Pipeline
- [ ] Run on all PRs
- [ ] Test on multiple Node versions (18, 20, 22)
- [ ] Test on multiple OS (Ubuntu, macOS, Windows)
- [ ] Run linting and type checking
- [ ] Build the project
- [ ] Run test suite (once implemented)

### CD Pipeline
- [ ] Trigger on push to main
- [ ] Use changesets for version management
- [ ] Automated npm publishing
- [ ] GitHub release creation
- [ ] Update changelog

## Implementation Tasks
1. Create `.github/workflows/ci.yml`
2. Create `.github/workflows/release.yml`
3. Set up npm token as GitHub secret
4. Configure changeset GitHub action
5. Test the full flow with a beta release

## Example Workflow Structure
```yaml
# .github/workflows/ci.yml
name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [18, 20, 22]
```

## Acceptance Criteria
- [ ] PRs cannot merge without passing CI
- [ ] Releases are automated and consistent
- [ ] Cross-platform compatibility verified
- [ ] npm package published successfully
